const global = require('./../../../../helper/global.js');

const scenario = ({
  getOK: {
    descCreateNoVariant: 'As a Vendor, I success to create Product No Variant',
    descCreateOneVariant: 'As a Vendor, I want to create Product 1 Variant',
    descCreateTwoVariant: 'As a Vendor, I success to create Product 2 Variant',
    descCreateNoVariantMandatory: 'As a Vendor, I want to create Product No Variant (Mandatory Only)',
    descCreateOneVariantMandatory: 'As a Vendor, I want to create Product 1 Variant (Mandatory Only)',
    descCreateTwoVariantMandatory: 'As a Vendor, I want to create Product 2 Variant (Mandatory Only)',
    descCreateNoVariantWithPG: 'As a Vendor, I want to create Product No Variant With Product Group',
    descCreateOneVariantWithPG: 'As a Vendor, I want to create Product 1 Variant With Product Group',
    descCreateTwoVariantWithPG: 'As a Vendor, I success to create Product 2 Variant With Product Group',
    descCreateNoVariantMandatoryWithPG: 'As a Vendor, I want to create Product No Variant (Mandatory Only) With Product Group',
    descCreateOneVariantMandatoryWithPG: 'As a Vendor, I want to create Product 1 Variant (Mandatory Only) With Product Group',
    descCreateTwoVariantMandatoryWithPG: 'As a Vendor, I want to create Product 2 Variant (Mandatory Only) With Product Group',
    descCreateTwoVariantWithPG1Tier: 'As a Vendor, I want to create Product 2 Variant With Product Group and only 1 tier and product indent',
    descCreateWithNewValueVariant: 'As a Vendor, I want to create Product With Product Group and new value in variant',
    activeDecimal: 'As a Vendor, I success to create Product With Product Group and set decimal sell as true',
    activateIndent: 'As a Vendor, I success to create Product With Product Group with indent status',
    activeDP: 'As a Vendor, I success to create Product With Product Group with indent status and setting down payment value',
    nonactiveDecimal: 'As a Vendor, I success to create Product With Product Group and set decimal sell as false',
    nonActiveIndent: 'As a Vendor, I success to create Product With Product Group and set indent status false',
    nonactiveDP: 'As a Vendor, I success to create Product With Product Group and activate indent status without set down payment value',
    nonactiveIndentAndNonactiveDP: 'As a Vendor, I success to create Product With Product Group and indent status false, without downpayment value',
    nominalDP: 'As a Vendor, I want to add product with active indent product and active nominal Down Payment',
    nonactiveIndentAndActiveDP: 'As a Vendor, I can add product with active Down Payment without activate indent product',
    responseCreate: global.response.created,
    response: global.response.ok,
  },
  getForbidden: {
    descInvalidVendorId: 'As, a vendor, I failed to create product with invalid vendor ID',
    response: global.response.forbidden,
  },
  getNotFound: {
    descInvalidPG: 'As a vendor, I can NOT create product with invalid Product Group ID',
    response: global.response.notFound,
  },
  getWithoutAuth: {
    descWithoutAuth: 'As a Vendor, I failed to create Product No Variant without auth',
    descTwoVariantWithPG: 'As a Vendor, I failed to create Product Two Variant without auth',
    response: global.response.unauthorized,

  },
  getInvalidAuth: {
    descOtherSession: 'As a Vendor, I failed to create Product No Variant with other user session',
    descOtherSessionTwoVariant: 'As a Vendor, I failed to create Product Two Variant with invalid user token',
    descInvalidSessionTwoVariant: 'As a Vendor, I failed to create Product Two Variant with invalid session',
    descOtherSessionTwoVariantWithPG: 'As a Vendor, I failed to create Product Two Variant (PG) with other user session',
    response: global.response.invalidAuth,
    responseForbidden: global.response.forbidden,
  },
  getBadRequest: {
    descTier2lessTier1: 'As a vendor, I can NOT create Product with QUANTITY Tier 2 LESS than Tier 1',
    descTier3lessTier2: 'As a vendor, I can NOT create Product with QUANTITY tier 3 LESS than Tier 2',
    descTier2sameTier1: 'As a vendor, I can NOT create Product with QUANTITY tier 2 SAME with Tier 1',
    descTier3sameTier2: 'As a vendor, I can NOT create Product with QUANTITY tier 3 SAME with Tier 2',
    descPrice2morePrice1: 'As a vendor, I can NOT create Product with PRICE Tier 2 MORE than Tier 1',
    descPrice3morePrice2: 'As a vendor, I can NOT create Product with PRICE Tier 3 MORE than Tier 2',
    descPrice2samePrice1: 'As a vendor, I can NOT create Product with PRICE Tier 2 SAME with Tier 1',
    descPrice3samePrice2: 'As a vendor, I can NOT create Product with PRICE Tier 3 SAME with Tier 2',
    emptyTier1: 'As a vendor, I can NOT create product with Empty value in Tier QUANTITY 1',
    emptyTier2: 'As a vendor, I can NOT create product with Empty value in Tier QUANTITY 2',
    emptyTier3: 'As a vendor, I can NOT create product with Empty value in Tier QUANTITY 3',
    emptyPrice1: 'As a vendor, I can NOT create product Tier PRICE 1 with Empty value',
    emptySKUVendor: 'As a vendor, I can NOT create product with Empty value in SKU vendor',
    existSKUVendor: 'As a vendor, I can NOT create product with exist value in SKU vendor',
    invalidSKUVendor: 'As a vendor, I can NOT create product with invalid value in SKU vendor',
    intTier1: 'As a vendor, I can NOT create product Tier QUANTITY 1 with Integer value',
    intTier2: 'As a vendor, I can NOT create product Tier QUANTITY2 with Integer value',
    intTier3: 'As a vendor, I can NOT create product Tier QUANTITY3 with Integer value',
    intPrice1: 'As a vendor, I can NOT create product Price 1 with Integer value',
    intPrice2: 'As a vendor, I can NOT create product Price 2 with Integer value',
    intPrice3: 'As a vendor, I can NOT create product Price 3 with Integer value',
    nonactiveIndentAndActiveDP: 'As a Vendor, I failed to create Product With Product Group without indent status but setting down payment value',
    invalidPercentageDP: 'As a Vendor, I failed to create Product With Product Group and invalid down payment percentage value',
    invalidNominalDP: 'As a Vendor, I failed to create Product With Product Group and invalid nominal down payment value',
    invalidIndentLimit: 'As a Vendor, I failed to create Product With Product Group and invalid indent limit value',
    // tier1WithoutPrice1: 'Update Tier QUANTITY 1 without fill tier price 1',
    // tier2WithoutPrice2: 'Update Tier QUANTITY 2 without fill tier price 2',
    // tier3WithoutPrice3: 'Update Tier QUANTITY 3 without fill tier price 3',
    // price1WithoutTier1: 'Update Tier PRICE 1 without fill tier quantity 1',
    // price2WithoutTier2: 'Update Tier PRICE 2 without fill tier quantity 2',
    // price3WithoutTier3: 'Update Tier PRICE 3 without fill tier quantity 3',
    invalidPercentageDP: 'As a Vendor, I can NOT add product with invalid percentage Down Payment',
    invalidNominalDP: 'As a Vendor, I can NOT add product with invalid nominal Down Payment',
    invalidIndentLimit: 'As a Vendor, I can NOT add product with indent limit more than 1 year',
    response: global.response.badRequest,
  },
});

module.exports = {
  scenario,
};
