const respMesCode = require('./../../helper/responseMessageAndCode.json');

const scenario = ({
  postSuccess: {
    successPostPublicCatalogLimitEven: 'should success post public catalog with limit even',
    successPostPublicCatalogLimitOdd: 'should success post public catalog with limit odd',
    successPostPublicCatalogSearchCategoryName: 'should success post public catalog with search category name',
    successPostPublicCatalogC0Decoration: 'should success post public catalog filter by category Dekorasi dan Elektronik Rumah Tangga',
    successPostPublicCatalogC0Electronic: 'should success post public catalog filter by category Elektronik Industri',
    successPostPublicCatalogC0Furniture: 'should success post public catalog filter by category Furnitur dan Perabotan',
    successPostPublicCatalogC0Gift: 'should success post public catalog filter by category Hadiah, Barang Promosi, dan Jasa Profesional',
    successPostPublicCatalogC0IT: 'should success post public catalog filter by category IT & Teknologi',
    successPostPublicCatalogC0Transportation: 'should success post public catalog filter by category Jasa Transportasi, Kargo dan Industri',
    successPostPublicCatalogC0MRO: 'should success post public catalog filter by category MRO (Maintenace, Repair, & Overhaul',
    successPostPublicCatalogC0Otomotif: 'should success post public catalog filter by category Otomotif dan Transportasi',
    successPostPublicCatalogC0Pantry: 'should success post public catalog filter by category Pantry, Kebersihan dan Kesehatan',
    successPostPublicCatalogC0EquipmentHotel: 'should success post public catalog filter by category Peralatan Hotel, Restoran & Kafe',
    successPostPublicCatalogC0Camera: 'should success post public catalog filter by category Percetakan, Kamera dan Audio-Visual',
    successPostPublicCatalogC0Office: 'should success post public catalog filter by category Perlengkapan Kantor',
    successPostPublicCatalogC0Agriculture: 'should success post public catalog filter by category Pertanian dan perkebunan',
    successPostPublicCatalogC0Surveillance: 'should success post public catalog filter by category Sistem Pengawasan dan Keamanan',
    successPostPublicCatalogC0DecorationandBrand: 'should success post public catalog filter by category Dekorasi dan Elektronik Rumah Tangga and brand',
    successPostPublicCatalogC0ElectronicandBrand: 'should success post public catalog filter by category Elektronik Industri and brand',
    successPostPublicCatalogC0FurnitureandBrand: 'should success post public catalog filter by category Furnitur dan Perabotan and brand',
    successPostPublicCatalogC0GiftandBrand: 'should success post public catalog filter by category Hadiah, Barang Promosi, dan Jasa Profesional and brand',
    successPostPublicCatalogC0ITandBrand: 'should success post public catalog filter by category IT & Teknologi and brand',
    successPostPublicCatalogC0TransportationandBrand: 'should success post public catalog filter by category Jasa Transportasi, Kargo dan Industri and brand',
    successPostPublicCatalogC0MROandBrand: 'should success post public catalog filter by category MRO (Maintenace, Repair, & Overhaul and brand',
    successPostPublicCatalogC0OtomotifandBrand: 'should success post public catalog filter by category Otomotif dan Transportasi and brand',
    successPostPublicCatalogC0PantryandBrand: 'should success post public catalog filter by category Pantry, Kebersihan dan Kesehatan and brand',
    successPostPublicCatalogC0EquipmentHotelandBrand: 'should success post public catalog filter by category Peralatan Hotel, Restoran & Kafe and brand',
    successPostPublicCatalogC0CameraandBrand: 'should success post public catalog filter by category Percetakan, Kamera dan Audio-Visual and brand',
    successPostPublicCatalogC0OfficeandBrand: 'should success post public catalog filter by category Perlengkapan Kantor and brand',
    successPostPublicCatalogC0AgricultureandBrand: 'should success post public catalog filter by category Pertanian dan perkebunan and brand',
    successPostPublicCatalogC0SurveillanceandBrand: 'should success post public catalog filter by category Sistem Pengawasan dan Keamanan and brand',
    successPostPublicCatalogC1fromC0Decoration: 'should success post public catalog filter by category C1 from category Dekorasi dan Elektronik Rumah Tangga',
    successPostPublicCatalogC1fromC0Electronic: 'should success post public catalog filter by category C1 from category Elektronik Industri',
    successPostPublicCatalogC1fromC0Furniture: 'should success post public catalog filter by category C1 from category Furnitur dan Perabotan',
    successPostPublicCatalogC1fromC0Gift: 'should success post public catalog filter by category C1 from category Hadiah, Barang Promosi, dan Jasa Profesional',
    successPostPublicCatalogC1fromC0IT: 'should success post public catalog filter by category C1 from category IT & Teknologi',
    successPostPublicCatalogC1fromC0Transportation: 'should success post public catalog filter by category C1 from category Jasa Transportasi, Kargo dan Industri',
    successPostPublicCatalogC1fromC0MRO: 'should success post public catalog filter by category C1 from category MRO (Maintenace, Repair, & Overhaul',
    successPostPublicCatalogC1fromC0Otomotif: 'should success post public catalog filter by category C1 from category Otomotif dan Transportasi',
    successPostPublicCatalogC1fromC0Pantry: 'should success post public catalog filter by category C1 from category Pantry, Kebersihan dan Kesehatan',
    successPostPublicCatalogC1fromC0EquipmentHotel: 'should success post public catalog filter by category C1 from category Peralatan Hotel, Restoran & Kafe',
    successPostPublicCatalogC1fromC0Camera: 'should success post public catalog filter by category C1 from category Percetakan, Kamera dan Audio-Visual',
    successPostPublicCatalogC1fromC0Office: 'should success post public catalog filter by category C1 from category Perlengkapan Kantor',
    successPostPublicCatalogC1fromC0Agriculture: 'should success post public catalog filter by category C1 from category Pertanian dan perkebunan',
    successPostPublicCatalogC1fromC0Surveillance: 'should success post public catalog filter by category C1 from category Sistem Pengawasan dan Keamanan',
    successPostPublicCatalogC1fromC0DecorationandBrand: 'should success post public catalog filter by category C1 from category Dekorasi dan Elektronik Rumah Tangga and brand',
    successPostPublicCatalogC1fromC0ElectronicandBrand: 'should success post public catalog filter by category C1 from category Elektronik Industri and brand',
    successPostPublicCatalogC1fromC0FurnitureandBrand: 'should success post public catalog filter by category C1 from category Furnitur dan Perabotan and brand',
    successPostPublicCatalogC1fromC0GiftandBrand: 'should success post public catalog filter by category C1 from category Hadiah, Barang Promosi, dan Jasa Profesional and brand',
    successPostPublicCatalogC1fromC0ITandBrand: 'should success post public catalog filter by category C1 from category IT & Teknologi and brand',
    successPostPublicCatalogC1fromC0TransportationandBrand: 'should success post public catalog filter by category C1 from category Jasa Transportasi, Kargo dan Industri and brand',
    successPostPublicCatalogC1fromC0MROandBrand: 'should success post public catalog filter by category C1 from category MRO (Maintenace, Repair, & Overhaul and brand',
    successPostPublicCatalogC1fromC0OtomotifandBrand: 'should success post public catalog filter by category C1 from category Otomotif dan Transportasi and brand',
    successPostPublicCatalogC1fromC0PantryandBrand: 'should success post public catalog filter by category C1 from category Pantry, Kebersihan dan Kesehatan and brand',
    successPostPublicCatalogC1fromC0EquipmentHotelandBrand: 'should success post public catalog filter by category C1 from category Peralatan Hotel, Restoran & Kafe and brand',
    successPostPublicCatalogC1fromC0CameraandBrand: 'should success post public catalog filter by category C1 from category Percetakan, Kamera dan Audio-Visual and brand',
    successPostPublicCatalogC1fromC0OfficeandBrand: 'should success post public catalog filter by category C1 from category Perlengkapan Kantor and brand',
    successPostPublicCatalogC1fromC0AgricultureandBrand: 'should success post public catalog filter by category C1 from category Pertanian dan perkebunan and brand',
    successPostPublicCatalogC1fromC0SurveillanceandBrand: 'should success post public catalog filter by category C1 from category Sistem Pengawasan dan Keamanan and brand',
    successPostPublicCatalogCategoryNameAndSearchProductNameAndMultipleBrand: 'should success post public catalog with filter Category Name, Brand Name, and search product name',
    successPostPublicCatalogWithOneBrand: 'should success post public catalog filter by category and one brand',
    successPostPublicCatalogWithMulitipleBrand: 'should success post public catalog filter by category and multiple brand',
    successPostPublicCatalogInvalidSearchCategoryName: 'should success post public catalog with invalid search product name',
    successPostPublicCatalogInvalidFilterCategoryName: 'should success post public catalog with invalid filter category name',
    successPostPublicCatalogInvalidFilterBrand: 'should success post public catalog with invalid filter brand',
    successPostPublicCatalogCategoryNameAndBrandNameAndInvalidSerch: 'should success post public catalog with filter Category Name, Brand Name, and invalid search product name',
    successPostPublicCatalogSearchSKU: 'should success post public catalog search by SKU',
    response: respMesCode.successOk,
  },
  postFailed: {
    failedPostWithInvalidKey: 'post error when API key invalid',
    failedPostWithBlankKey: 'post error when API key blank',
    response: respMesCode.failedForbiddenInvalidToken.codeNumber,
  }
});

module.exports = {
  scenario,
};